// onegate_21_login_notification212/src/App.vue
<template>
  <v-app id="app_login">
    <div @click="showNoti"
      v-if="drawer"
      style="position: fixed;width: 100%;height: 100vh;left: 0;top: 0;"></div>
    <div v-if="!isSignedIn" style="
        position: relative;
        height: 50px;
    ">
    <div class="login-wrapper">
      <div class="login-input">
        <div class="ico ico-user">
          <input type="text" placeholder="Tài khoản đăng nhập" name="_LoginNotification_login">
        </div>
        <div class="ico ico-pass">
          <input type="text" placeholder="Mật khẩu" name="_LoginNotification_password">
        </div>
      </div>
      <div class="login-input">
        <div style="width: 100%;">
          <a href="/forgotten-password" class="text-hover-blue" style="
              line-height: 30px;
              font-size: 12px;
              color: #005792;
              text-decoration: underline;
              padding-left: 10px;
          ">Quên mật khẩu?</a>
        </div> 
        <div style="
          width: 100%;
          text-align: right;
        ">
          <button type="button" @click="doRegisterRedirect" class="btn-register">Đăng ký</button>
          <button type="submit" class="btn-login">Đăng nhập</button>
        </div>
      </div>
    </div>
    </div>
    <div v-else>
      
      <div style="text-align: right;">
        <v-badge color="red" v-if="notificationCount > 0">
          <span @click="showNoti" slot="badge">2</span>
          <v-btn icon @click="showNoti" class="mx-0 my-0">
            <v-icon
              size="20"
              color="blue darken-3"
              class="swing animated"
              style="-webkit-animation: swing 0.8s infinite;animation: swing 0.8s infinite;"
            >
              notifications_active
            </v-icon>
          </v-btn>
        </v-badge>
        <v-btn v-else icon @click="showNoti" class="mx-0 my-0" style="margin-right: -10px !important">
            <v-icon
              size="20"
              color="blue darken-3"
              class="swing animated"
              style="-webkit-animation: swing 0.8s infinite;animation: swing 0.8s infinite;"
            >
              notifications
            </v-icon>
          </v-btn>
        <v-menu offset-y :nudge-bottom="5">
          <v-chip slot="activator" @click="isShowUserMenu = !isShowUserMenu">
            <v-avatar>
              <img :src="avatarURL">
            </v-avatar>
            {{userNameLogin}}
            <v-icon
              v-if="!isShowUserMenu"
              size="20"
              color="blue darken-3"
              class="swing animated"
            >
              expand_more
            </v-icon>
            <v-icon
              v-else
              size="20"
              color="blue darken-3"
              class="swing animated"
            >
              expand_less
            </v-icon>
          </v-chip>
          <v-list>
            <v-list-tile @click="doUserInfo">
              <v-list-tile-action>
                <v-icon size="16">person</v-icon>
              </v-list-tile-action>
              <v-list-tile-content>
                <v-list-tile-title>Thông tin tài khoản</v-list-tile-title>
              </v-list-tile-content>
            </v-list-tile>
            <v-list-tile @click="doExitApp">
              <v-list-tile-action>
                <v-icon size="16" color="red darken-3">exit_to_app</v-icon>
              </v-list-tile-action>
              <v-list-tile-content>
                <v-list-tile-title>Đăng xuất</v-list-tile-title>
              </v-list-tile-content>
            </v-list-tile>
          </v-list>
        </v-menu>
      </div>
      
      <v-navigation-drawer
        v-model="drawer"
        temporary
        fixed
        clipped
        right
        hide-overlay
      >
        <v-list class="pa-1">
          <v-list-tile>
            <v-list-tile-content>
              <v-btn-toggle style="width: 100%;" v-model="toggle_exclusive" mandatory>
                <v-btn block flat class="px-0">
                  Hôm nay
                </v-btn>
                <v-btn block flat class="px-0">
                  Thông báo mới
                </v-btn>
              </v-btn-toggle>
            </v-list-tile-content>
          </v-list-tile>
        </v-list>
  
        <v-list class="pt-0" dense>
          <v-divider></v-divider>
  
          <!--
          <v-list-tile>

            <v-list-tile-content>
              <v-list-tile-title>Yesterday</v-list-tile-title>
            </v-list-tile-content>

            <v-list-tile-action>
              <v-btn small icon class="mx-0 my-0" color="grey darken-2">
                <v-icon size="14" style="color: #fff;">clear</v-icon>
              </v-btn>
            </v-list-tile-action>
            
          </v-list-tile>
          <div style="padding: 2px 12px 8px 12px;"><div style="
    border-radius: 7px;
    background: #f3f3f3;
"><div style="
    background: #eaeaea;
    padding: 5px 10px;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
">
                  Thong bao moi
                </div> <div style="
    padding: 10px;
">
                  abc
                </div></div></div>

          <div style="padding: 2px 12px 8px 12px;"><div style="
    border-radius: 7px;
    background: #f3f3f3;
"><div style="
    background: #eaeaea;
    padding: 5px 10px;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
">
                  Thong bao moi
                </div> <div style="
    padding: 10px;
">
                  abc
                </div></div></div>
            
          <div style="padding: 2px 12px 8px 12px;"><div style="
    border-radius: 7px;
    background: #f3f3f3;
"><div style="
    background: #eaeaea;
    padding: 5px 10px;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
">
                  Thong bao moi
                </div> <div style="
    padding: 10px;
">
                  abc
                </div></div></div>

              -->
        </v-list>
      </v-navigation-drawer>
    </div>
  </v-app>
</template>

<script>
  import axios from 'axios'
  export default {
    data: () => ({
      isSignedIn: false,
      userNameLogin: '',
      drawer: false,
      avatarURL: 'http://via.placeholder.com/350x150',
      notificationCount: 0,
      isShowUserMenu: false,
      toggle_exclusive: 0
    }),
    created () {
      let vm = this
      vm.$nextTick(function () {
        vm.isSignedIn = themeDisplay.isSignedIn()
        vm.userNameLogin = themeDisplay.getUserName()
        if (vm.isSignedIn) {
          let param = {
            responseType: 'blob'
          }
          axios.get('/o/rest/v2/users/' + themeDisplay.getUserId() + '/photo', param).then(function (response) {
            vm.avatarURL = window.URL.createObjectURL(response.data)
          }).catch(function (error) {
            reject(error)
          })
        }
      })
    },
    methods: {
      showNoti () {
        let vm = this
        vm.drawer = !vm.drawer
      },
      doRegisterRedirect () {
        let redirectURL = themeDisplay.getLayoutRelativeURL().substring(0, themeDisplay.getLayoutRelativeURL().lastIndexOf('\/'))
        if (redirectURL !== '') {
          window.location.href = redirectURL + '/register'
        } else {
          window.location.href = themeDisplay.getURLHome() + '/register'
        }
      },
      doUserInfo () {
        let redirectURL = themeDisplay.getLayoutRelativeURL().substring(0, themeDisplay.getLayoutRelativeURL().lastIndexOf('\/'))
        window.location.href = redirectURL + '/profile'
      },
      doExitApp () {
        window.location.href = '/c/portal/logout'
      }
    }
  }
</script>

// react-simple-app-master/src/App.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Badge from '@material-ui/core/Badge';
import IconButton from '@material-ui/core/IconButton';
import Avatar from '@material-ui/core/Avatar';
import Chip from '@material-ui/core/Chip';
import Menu from '@material-ui/core/Menu';
import MenuItem from '@material-ui/core/MenuItem';
import Grow from '@material-ui/core/Grow';
import Grid from '@material-ui/core/Grid';
import axios from 'axios';
import NotificationsActiveIcon from '@material-ui/icons/NotificationsActive';
import ExitToAppIcon from '@material-ui/icons/ExitToApp';
import PersonIcon from '@material-ui/icons/Person';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import withRoot from './withRoot';
import { withStyles } from '@material-ui/core/styles';
import deepOrange from '@material-ui/core/colors/deepOrange';
import Button from '@material-ui/core/Button';

const themeDisplay = window.themeDisplay;

const styles = theme => ({
  root: {
    textAlign: 'right',
    paddingTop: theme.spacing.unit * 0,
  },
  orangeAvatar: {
    marginTop: 8,
    color: '#fff',
    backgroundColor: deepOrange[500],
    width: 32,
    height: 32,
    fontSize: 14,
    fontWeight: '800',
  },
  btnNameAvata: {
    marginTop: 9,
    fontSize: 13,
    borderRadius: 28,
    marginLeft: -32,
    padding: '3px 12px',
    minHeight: 0,
    paddingLeft: 38,
    '-webkit-box-shadow': '0 4px 4px -4px rgba(0,0,0,.1), 0 0px 0px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0, 0.12)',
    boxShadow: '0 4px 4px -4px rgba(0,0,0,.1), 0 0px 0px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0, 0.12)'
  }
});

const pStyle = {
  top: '60px',
  right: '8%',
};

const chipStyle = {
  marginTop: '5px',
  marginLeft: '5px',
  backgroundColor: 'transparent'
};

const exitToAppStyle = {
  width: '15px',
  marginRight: '10px',
  color: '#C62828'
};

const userInfoStyle = {
  width: '15px',
  marginRight: '10px'
};

const btnNotiStyle = {
  height: '42px',
  width: '42px'
};

class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      open: false,
      anchorEl: null,
      isSignedIn: false,
      userNameLogin: '',
      forgottenURL: '/forgotten-password',
      drawer: false,
      avatarURL: '',
      notificationCount: 0,
      isShowUserMenu: false,
      toggle_exclusive: 0
    };
    this.handleClick = this.handleClick.bind(this);
    this.handleToggle = this.handleToggle.bind(this);
    this.handleClose = this.handleClose.bind(this);
  }

  handleToggle() {
    this.setState(state => ({ open: !state.open }));
  };

  handleClose() {
    this.setState({
      open: false,
    });
  };

  handleClick(event) {
    this.setState({ anchorEl: event.currentTarget });
  };

  componentDidMount() {
    let vm = this
    if (themeDisplay !== null && themeDisplay !== undefined) {
      let redirectURL = themeDisplay.getLayoutRelativeURL().substring(0, themeDisplay.getLayoutRelativeURL().lastIndexOf('\/'))
      let forgottenURLStr = ''
      if (redirectURL !== '') {
        forgottenURLStr = redirectURL + '/forgotten-password'
      } else {
        forgottenURLStr = themeDisplay.getURLHome() + '/forgotten-password'
      }
      vm.setState({
        isSignedIn: themeDisplay.isSignedIn(),
        userNameLogin: themeDisplay.getUserName(),
        forgottenURL: forgottenURLStr
      })
      if (themeDisplay.isSignedIn()) {
        let param = {
          responseType: 'blob'
        }
        axios.get('/o/rest/v2/users/' + themeDisplay.getUserId() + '/photo', param).then(function (response) {
          let avatarURLStr = window.URL.createObjectURL(response.data)
          vm.setState({ avatarURL: avatarURLStr })
        }).catch(function (error) {
          console.log(error)
        })
      }
    }
  };

  goToDangKyPage() {
    if (themeDisplay !== null && themeDisplay !== undefined) {
      // eslint-disable-next-line
      let redirectURL = themeDisplay.getLayoutRelativeURL().substring(0, themeDisplay.getLayoutRelativeURL().lastIndexOf('\/'))
      if (redirectURL !== '') {
        window.location.href = redirectURL + '/register'
      } else {
        window.location.href = themeDisplay.getURLHome() + '/register'
      }
    } else {
      window.location.href = '/register'
    }
  };

  doUserInfo() {
    if (themeDisplay !== null && themeDisplay !== undefined) {
      // eslint-disable-next-line
      let redirectURL = themeDisplay.getLayoutRelativeURL().substring(0, themeDisplay.getLayoutRelativeURL().lastIndexOf('\/'))
      window.location.href = redirectURL + '/profile'
    } else {
      window.location.href = '/profile'
    }
  };
  
  doExitApp() {
    window.location.href = '/c/portal/logout'
  };

  render() {
    const { classes } = this.props;
    const { open, isSignedIn, userNameLogin, avatarURL, notificationCount, forgottenURL, anchorEl } = this.state;
    
    return (
      <div>
        { !isSignedIn ? 
          <div className="login-wrapper">
            <div className="login-input">
              <div className="ico ico-user">
                <input type="text" placeholder="Tài khoản đăng nhập" name="_npmreactlogin_login" />
              </div>
              <div className="ico ico-pass">
                <input type="password" placeholder="Mật khẩu" name="_npmreactlogin_password" />
              </div>
            </div>
            <div className="login-input">
              <div className="forgetten-password-input">
                <a href={forgottenURL} className="text-hover-blue">Quên mật khẩu?</a>
              </div> 
              <div className="action-btn-login-input">
                <button onClick={this.goToDangKyPage} type="button" className="btn-register">Đăng ký</button>
                <button type="submit" className="btn-login">Đăng nhập</button>
              </div>
            </div>
          </div>
        : 
        <Grid container>
          <Grid item>
            <IconButton style={btnNotiStyle} className={classes.margin}>
            { notificationCount > 0 ? 
              <Badge badgeContent={notificationCount} color="secondary">
                <NotificationsActiveIcon color="primary" />
              </Badge>
            :
              <NotificationsActiveIcon color="primary" />
            }
            </IconButton>
          </Grid>
          <Grid item>
            { avatarURL === '' ? 
              <Grid container>
                <Grid item>
                <Avatar className={classes.orangeAvatar}>N</Avatar>
                </Grid>
                <Grid item>
                <Button
                  aria-haspopup="true"
                  onClick={this.handleToggle}
                  className={classes.btnNameAvata}
                >
                  {userNameLogin}
                  <ExpandMoreIcon />
                </Button>
                </Grid>
              </Grid>
            :
              <Chip
                onClick={this.handleToggle}
                avatar={<Avatar src={avatarURL} />}
                label={userNameLogin}
                className={classes.chip}
                style={chipStyle}
                onDelete={this.handleToggle}
                deleteIcon={<ExpandMoreIcon />}
              />
            }
            <Menu
              id="fade-menu"
              className="user-profile-menu-react"
              anchorEl={this.anchorEl}
              open={open}
              onClose={this.handleClose}
              TransitionComponent={Grow}
              style={pStyle}
            >
              <MenuItem onClick={this.doUserInfo}> <PersonIcon style={userInfoStyle}/> Thông tin tài khoản</MenuItem>
              <MenuItem onClick={this.doExitApp}> <ExitToAppIcon style={exitToAppStyle}/> Đăng xuất</MenuItem>
            </Menu>
          </Grid>
        </Grid>
        }
      </div>
    );
  }
}

App.propTypes = {
  classes: PropTypes.object.isRequired,
};

export default withRoot(withStyles(styles)(App));
